function [reportPath, htmlContent] = generateClinicalReport(varargin)
% GENERATECLINICALREPORT  Generate a full rich HTML clinical report for DR screening.
%
% Syntax:
%   [reportPath, htmlContent] = generateClinicalReport(patientInfo, img, iqaResult,
%       segResults, gradeResult, dmeRisk, dmeScore, dmeExpl, overlay, outputPath)
%
% Reference:
%   MathWorks SIH - Explainable AI for DR Screening in Rural PHCs

    reportPath  = '';
    htmlContent = '';

    % ---- Parse arguments ----
    patientInfo = struct();
    iqaResult   = struct('qualityCategory','Unknown','overallScore',0);
    segResults  = struct();
    gradeResult = struct('gradeLabel','Unknown','confidence',0,'isReferable',false,'explanation','');
    dmeRisk     = 'Unknown';
    dmeScore    = 0;
    dmeExpl     = '';
    outputPath  = fullfile('.', 'DR_Clinical_Report.html');

    if nargin >= 1 && ~isempty(varargin{1}), patientInfo = varargin{1}; end
    % varargin{2} = img (unused in HTML)
    if nargin >= 3 && isstruct(varargin{3}), iqaResult   = varargin{3}; end
    if nargin >= 4 && isstruct(varargin{4}), segResults  = varargin{4}; end
    if nargin >= 5 && isstruct(varargin{5}), gradeResult = varargin{5}; end
    if nargin >= 6 && (ischar(varargin{6}) || isstring(varargin{6})), dmeRisk  = char(varargin{6}); end
    if nargin >= 7 && isnumeric(varargin{7}), dmeScore = varargin{7}; end
    if nargin >= 8 && (ischar(varargin{8}) || isstring(varargin{8})), dmeExpl  = char(varargin{8}); end
    % varargin{9} = overlay (unused)
    if nargin >= 10
        lastArg = varargin{10};
        if ischar(lastArg) || isstring(lastArg), outputPath = char(lastArg); end
    end

    % ---- Extract patient ID ----
    pID = 'UNKNOWN';
    if isstruct(patientInfo)
        for f = {'PatientID','patientID','id','name'}
            if isfield(patientInfo, f{1}), pID = char(patientInfo.(f{1})); break; end
        end
    elseif ischar(patientInfo) || isstring(patientInfo)
        pID = char(patientInfo);
    end

    % ---- Extract IQA values ----
    iqaCat   = 'Unknown';
    iqaScore = 0;
    if isstruct(iqaResult)
        if isfield(iqaResult,'qualityCategory'), iqaCat   = char(iqaResult.qualityCategory); end
        if isfield(iqaResult,'overallScore'),    iqaScore = iqaResult.overallScore; end
    end

    % ---- Extract grade / referral ----
    gradeLabel  = 'Unknown';
    confidence  = 0;
    isReferable = false;
    explanation = '';
    gradeNum    = -1;
    if isstruct(gradeResult)
        if isfield(gradeResult,'gradeLabel'),  gradeLabel  = char(gradeResult.gradeLabel);  end
        if isfield(gradeResult,'confidence'),  confidence  = gradeResult.confidence;         end
        if isfield(gradeResult,'isReferable'), isReferable = gradeResult.isReferable;        end
        if isfield(gradeResult,'explanation'), explanation = char(gradeResult.explanation);  end
        if isfield(gradeResult,'grade'),       gradeNum    = gradeResult.grade;              end
    end

    % ---- Extract biomarkers ----
    maCount   = 0; hmCount = 0; heArea = 0; nvFlag = false; vDensity = 0;
    if isstruct(segResults)
        if isfield(segResults,'maDetails') && isstruct(segResults.maDetails) && isfield(segResults.maDetails,'count')
            maCount = segResults.maDetails.count;
        end
        if isfield(segResults,'hmDetails') && isstruct(segResults.hmDetails) && isfield(segResults.hmDetails,'count')
            hmCount = segResults.hmDetails.count;
        end
        if isfield(segResults,'heArea'),       heArea   = round(segResults.heArea);    end
        if isfield(segResults,'nvDetails') && isstruct(segResults.nvDetails) && isfield(segResults.nvDetails,'detected')
            nvFlag = logical(segResults.nvDetails.detected);
        end
        if isfield(segResults,'vesselDensity'), vDensity = segResults.vesselDensity;  end
    end

    % ---- Colour coding ----
    if isReferable
        badgeBg   = '#c53030';
        badgeTxt  = 'URGENT SPECIALIST REFERRAL REQUIRED';
        gradeColor= '#c53030';
    else
        badgeBg   = '#276749';
        badgeTxt  = 'ROUTINE FOLLOW-UP — No Immediate Referral';
        gradeColor= '#276749';
    end

    nvStr  = ternaryStr(nvFlag,  'Detected ⚠️', 'Not Detected ✓');
    refStr = ternaryStr(isReferable, 'YES — Urgent Referral', 'NO — Routine Follow-up');
    nowStr = datestr(now, 'yyyy-mm-dd HH:MM');

    % ---- Build HTML ----
    css = [
        'body{font-family:"Segoe UI",Roboto,Helvetica,Arial,sans-serif;margin:0;'...
        'background:#edf2f7;color:#2d3748;}' ...
        '.wrap{max-width:960px;margin:24px auto;background:#fff;border-radius:10px;'...
        'box-shadow:0 4px 24px rgba(0,0,0,.10);overflow:hidden;}' ...
        '.top-bar{background:#1a365d;color:#fff;padding:18px 28px;display:flex;'...
        'justify-content:space-between;align-items:center;}' ...
        '.top-bar h1{margin:0;font-size:18px;font-weight:700;}' ...
        '.top-bar .sub{font-size:12px;opacity:.7;margin-top:3px;}' ...
        '.top-bar .ts{font-size:12px;text-align:right;opacity:.8;}' ...
        '.badge{margin:18px 28px 0;display:inline-block;padding:8px 18px;'...
        'border-radius:5px;font-weight:700;font-size:13px;color:#fff;}' ...
        '.body{padding:20px 28px 28px;}' ...
        '.grid2{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:16px 0;}' ...
        '.card{background:#f7fafc;border:1px solid #e2e8f0;border-radius:7px;padding:14px;}' ...
        '.card h3{margin:0 0 10px;font-size:13px;font-weight:700;color:#2b6cb0;'...
        'border-bottom:1px solid #e2e8f0;padding-bottom:6px;text-transform:uppercase;letter-spacing:.5px;}' ...
        'table{width:100%;border-collapse:collapse;}' ...
        'td,th{padding:5px 8px;font-size:13px;text-align:left;}' ...
        'th{background:#ebf4ff;font-weight:600;color:#2b6cb0;}' ...
        'tr:nth-child(even)td{background:#f0f4f8;}' ...
        '.bar-bg{background:#e2e8f0;border-radius:99px;height:8px;margin-top:4px;}' ...
        '.bar-fg{background:#3182ce;border-radius:99px;height:8px;}' ...
        '.alert{padding:11px 14px;border-radius:5px;font-size:13px;margin:10px 0;border-left:4px solid;}' ...
        '.alert-blue{background:#ebf8ff;border-color:#3182ce;}' ...
        '.alert-orange{background:#fffaf0;border-color:#dd6b20;}' ...
        '.alert-red{background:#fff5f5;border-color:#c53030;}' ...
        '.footer{border-top:1px solid #e2e8f0;padding:14px 28px;display:flex;'...
        'justify-content:space-between;font-size:12px;color:#718096;}' ...
        '@media print{body{background:#fff;}.wrap{box-shadow:none;}}' ...
    ];

    probNames = {'Grade 0','Grade 1','Grade 2','Grade 3','Grade 4'};
    % Build probability bar rows (5 grades, placeholder if not available)
    probRows = '';
    for gi = 0:4
        pct = 0;
        if gi == gradeNum, pct = round(confidence * 100); end
        barW = max(3, pct);
        probRows = [probRows sprintf( ...
            '<tr><td>%s</td><td style="width:120px"><div class="bar-bg">'...
            '<div class="bar-fg" style="width:%d%%"></div></div></td>'...
            '<td style="font-weight:%s;color:%s">%d%%</td></tr>', ...
            probNames{gi+1}, barW, ...
            ternaryStr(gi==gradeNum,'700','400'), ...
            ternaryStr(gi==gradeNum,'#c53030','#4a5568'), ...
            pct)];
    end

    % Biomarker severity indicators
    function s = severity(val, thLow, thHigh)
        if val == 0,         s = '<span style="color:#276749">None ✓</span>';
        elseif val < thLow,  s = '<span style="color:#d69e2e">Mild</span>';
        elseif val < thHigh, s = '<span style="color:#dd6b20">Moderate</span>';
        else,                s = '<span style="color:#c53030">Severe</span>';
        end
    end

    htmlContent = sprintf(['<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">' ...
        '<meta name="viewport" content="width=device-width,initial-scale=1">' ...
        '<title>DR Screening Report — %s</title>' ...
        '<style>%s</style></head><body>' ...
        '<div class="wrap">' ...
        '  <div class="top-bar">' ...
        '    <div><div class="sub">MathWorks SIH · Explainable AI for DR Screening · Rural PHC Tele-Ophthalmology</div>' ...
        '    <h1>Diabetic Retinopathy Clinical Screening Report</h1></div>' ...
        '    <div class="ts">%s<br><b>Rural PHC, Maharashtra</b></div>' ...
        '  </div>' ...
        '  <div class="badge" style="background:%s">%s</div>' ...
        '  <div class="body">' ...
        '    <div class="grid2">' ...
        '      <div class="card"><h3>Patient Information</h3><table>' ...
        '        <tr><td><b>Patient ID</b></td><td>%s</td></tr>' ...
        '        <tr><td><b>IQA Status</b></td><td><b>%s</b> (Score: %.1f / 100)</td></tr>' ...
        '        <tr><td><b>Image Gradeable</b></td><td>%s</td></tr>' ...
        '      </table></div>' ...
        '      <div class="card"><h3>AI Diagnostic Summary</h3><table>' ...
        '        <tr><td><b>ICDR Grade</b></td><td><b style="color:%s">%s</b></td></tr>' ...
        '        <tr><td><b>AI Confidence</b></td><td>%.1f%%</td></tr>' ...
        '        <tr><td><b>Referral Decision</b></td><td>%s</td></tr>' ...
        '        <tr><td><b>DME Risk</b></td><td><b>%s</b> (Score: %d/100)</td></tr>' ...
        '      </table></div>' ...
        '    </div>' ...
        '    <div class="grid2">' ...
        '      <div class="card"><h3>Explainable Biomarker Quantification</h3><table>' ...
        '        <thead><tr><th>Biomarker</th><th>Value</th><th>Severity</th></tr></thead><tbody>' ...
        '        <tr><td>Microaneurysms (MAs)</td><td><b>%d</b></td><td>%s</td></tr>' ...
        '        <tr><td>Hemorrhages (HMs)</td><td><b>%d</b></td><td>%s</td></tr>' ...
        '        <tr><td>Hard Exudates (HE)</td><td><b>%d px</b></td><td>%s</td></tr>' ...
        '        <tr><td>Vessel Density</td><td><b>%.1f%%</b></td><td>—</td></tr>' ...
        '        <tr><td>Neovascularization</td><td colspan="2"><b>%s</b></td></tr>' ...
        '        </tbody></table></div>' ...
        '      <div class="card"><h3>Grade Probability Distribution</h3><table>' ...
        '        <thead><tr><th>Grade</th><th>Confidence Bar</th><th>Pct</th></tr></thead><tbody>' ...
        '        %s' ...
        '        </tbody></table></div>' ...
        '    </div>' ...
        '    <div class="alert alert-blue"><b>Clinical Rationale (4-2-1 Rule):</b> %s</div>' ...
        '    <div class="alert alert-orange"><b>DME Analysis:</b> %s</div>' ...
        '  </div>' ...
        '  <div class="footer">' ...
        '    <div>Tele-Ophthalmologist: _______________________</div>' ...
        '    <div>Action: [&nbsp;&nbsp;] Confirmed &nbsp; [&nbsp;&nbsp;] Overruled &nbsp; [&nbsp;&nbsp;] Request OCT</div>' ...
        '    <div>Sub-30s SLA &nbsp;|&nbsp; %s</div>' ...
        '  </div>' ...
        '</div></body></html>'], ...
        pID, css, nowStr, ...
        badgeBg, badgeTxt, ...
        pID, iqaCat, iqaScore, ...
        ternaryStr(strcmp(iqaCat,'Gradeable'),'<b style="color:#276749">Yes ✓</b>','<b style="color:#c53030">No — Enhancement Applied</b>'), ...
        gradeColor, gradeLabel, confidence * 100, refStr, dmeRisk, dmeScore, ...
        maCount, severity(maCount, 5, 15), ...
        hmCount, severity(hmCount, 3, 15), ...
        heArea, severity(heArea, 50, 200), ...
        vDensity * 100, nvStr, ...
        probRows, ...
        ternaryStr(isempty(explanation), 'No specific rule triggered.', explanation), ...
        ternaryStr(isempty(dmeExpl), 'DME risk assessment not available.', dmeExpl), ...
        nowStr);

    % ---- Write to file ----
    % Ensure output directory exists
    outDir = fileparts(outputPath);
    if ~isempty(outDir) && exist(outDir, 'dir') ~= 7
        mkdir(outDir);
    end

    reportPath = outputPath;
    fid = fopen(reportPath, 'w');
    if fid ~= -1
        fprintf(fid, '%s', htmlContent);
        fclose(fid);
        fprintf('[generateClinicalReport] Report saved: %s\n', reportPath);
    else
        warning('generateClinicalReport: Could not write report to %s', reportPath);
    end
end

function s = ternaryStr(cond, a, b)
    if cond, s = a; else, s = b; end
end
